name: frontend validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-frontend-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Generate new frontend
        run: ./genfrontend.sh --yes --dev
      - name: Verify no changes
        run: |
          report="$(git status --porcelain)"
          if [ -n "$report" ]; then
            git diff --output=./changes.diff
            cat changes.diff >&2
            echo "FAILED: frontend generation results in code changes." >&2
            echo "Run './genfrontend.sh' on codebase and try again." >&2
            exit 1
          else
            echo "PASS: frontend does not have pending updates"
          fi
